# -*- coding: utf-8 -*-
"""demo1.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3EtgmRlppuLZh8Za7gyPOJJxRrD7iuD
"""

#cell 1
!pip install cpca airportsdata

# ════════════════════════════════════════════════════════════
#  标准库 / 第三方导入
# ════════════════════════════════════════════════════════════
from __future__ import annotations

import io
import re
import warnings
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any, Callable

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output


def _is_colab() -> bool:
    """判断当前是不是在 Google Colab 环境运行。"""
    try:
        import google.colab
        return True
    except ImportError:
        return False
# ════════════════════════════════════════════════════════════
# 【核心状态类】：AppState (整个应用的数据管家)
# 作用：它就像一个中央仓库，存着所有模块共用的数据，保证大家信息同步。
# ════════════════════════════════════════════════════════════
# ─────────────────────────────────────────────
#  模块槽描述符：每个业务模块声明自己的 key + 默认值工厂  ---注册式容器
# ─────────────────────────────────────────────
@dataclass
class SlotSpec:
    """
    描述一个业务字段：
      key          – 全局唯一名称，模块自己定，建议加前缀（'traj_matched_plates'）
      default_factory – 无参可调用，返回该字段的初始值
      description  – 可选说明，方便调试时理解每个 key 的含义
    """
    key: str
    default_factory: Callable[[], Any]
    description: str = ""


# ─────────────────────────────────────────────
#  AppState：通用注册容器
# ─────────────────────────────────────────────
class AppState:
    """
    全程序数据核心 —— 通用注册容器版本。

    设计原则
    --------
    * AppState 本身永远不修改字段定义。
    * 各业务模块在自己的文件里调用 `AppState.register(specs)` 声明所需字段。
    * 运行时通过 `state['key']` / `state['key'] = value` 读写，
      也可用属性风格 `state.key` / `state.key = value`（便于兼容旧代码）。
    * `state.reset()` 自动重置所有已注册字段到默认值，无需手动维护。

    快速上手
    --------
    # 1. 模块声明自己的字段（在模块文件顶部执行一次即可）
    AppState.register([
        SlotSpec('traj_matched_plates', list,         '模糊搜索出来的车牌号'),
        SlotSpec('traj_trajectories',   pd.DataFrame, '车牌对应的详细轨迹记录'),
    ])

    # 2. 读写
    state = AppState.instance()
    state['traj_matched_plates'] = ['粤A·12345']
    plates = state['traj_matched_plates']

    # 3. 重置（自动覆盖全部注册字段）
    state.reset()
    """

    # ── 类级别注册表：key -> SlotSpec（所有实例共享同一份 schema）
    _registry: dict[str, SlotSpec] = {}

    # ── 单例（Notebook 场景下通常只需一个全局状态）
    _singleton: "AppState | None" = None

    # ────────────────────────────────
    #  类方法：注册 / 单例获取
    # ────────────────────────────────

    @classmethod
    def instance(cls) -> "AppState":
        """获取全局单例，首次调用时自动创建并初始化所有已注册字段。"""
        if cls._singleton is None:
            cls._singleton = cls()
        return cls._singleton

    @classmethod
    def registered_keys(cls) -> list[str]:
        """返回当前所有已注册的 key，方便调试。"""
        return list(cls._registry.keys())
    @classmethod
    def register(cls, specs: list[SlotSpec]) -> None:
      """
      业务模块调用此方法声明所需字段。
      重复注册同一 key 会跳过（幂等），支持模块热重载场景。
      若单例已存在，新字段会立即补入 _store。
      """
      for spec in specs:
          if spec.key not in cls._registry:
              cls._registry[spec.key] = spec
              if cls._singleton is not None:
                  store = object.__getattribute__(cls._singleton, '_store')
                  store[spec.key] = spec.default_factory()
    # ────────────────────────────────
    #  实例初始化
    # ────────────────────────────────
    def __init__(self) -> None:
        # 运行时数据集，外部不直接访问
        object.__setattr__(self, '_store', {})
        self._init_all()

    def _init_all(self) -> None:
        """按注册表将所有字段初始化为默认值。"""
        store: dict = object.__getattribute__(self, '_store')
        for key, spec in self._registry.items():
            store[key] = spec.default_factory()

    # ────────────────────────────────
    #  读写接口（字典风格）
    # ────────────────────────────────
    def __getitem__(self, key: str) -> Any:
        store: dict = object.__getattribute__(self, '_store')
        if key not in self._registry:
            raise KeyError(f"[AppState] '{key}' 未注册，请先调用 AppState.register()。")
        return store[key]

    def __setitem__(self, key: str, value: Any) -> None:
        store: dict = object.__getattribute__(self, '_store')
        if key not in self._registry:
            raise KeyError(f"[AppState] '{key}' 未注册，请先调用 AppState.register()。")
        store[key] = value

    # ────────────────────────────────
    #  读写接口（属性风格，兼容旧代码）
    # ────────────────────────────────
    def __getattr__(self, key: str) -> Any:
        # __getattr__ 只在普通查找失败时触发，不会影响 _store 等私有属性
        try:
            return self[key]
        except KeyError:
            raise AttributeError(f"[AppState] 属性 '{key}' 未注册。") from None

    def __setattr__(self, key: str, value: Any) -> None:
        if key.startswith('_'):
            object.__setattr__(self, key, value)
        else:
            self[key] = value

    # ────────────────────────────────
    #  其他实用方法
    # ────────────────────────────────
    def reset(self) -> None:
        """一键重置所有已注册字段到默认值。新增模块无需改这里。"""
        self._init_all()

    def snapshot(self) -> dict[str, Any]:
        """返回当前所有字段的浅拷贝，方便调试或序列化。"""
        store: dict = object.__getattribute__(self, '_store')
        return dict(store)

    def __repr__(self) -> str:
        store: dict = object.__getattribute__(self, '_store')
        lines = [f"AppState ({len(self._registry)} 个已注册字段):"]
        for key, spec in self._registry.items():
            val = store.get(key, '<未初始化>')
            preview = repr(val)[:60] + ("…" if len(repr(val)) > 60 else "")
            lines.append(f"  {key:<35} = {preview}")
            if spec.description:
                lines.append(f"  {'':35}   # {spec.description}")
        return "\n".join(lines)

# ════════════════════════════════════════════════════════════
# 【抽象标准】：DataSource / AnalysisModule / UIComponent
# 作用：这是给各功能模块定下的“规矩”，确保大家开发模式统一，规定各模块遵循的契约。
# ════════════════════════════════════════════════════════════
class DataSource(ABC):
    """规定数据源怎么加载数据。"""
    @abstractmethod
    def load(self, content: bytes, filename: str) -> pd.DataFrame: ...
    @abstractmethod
    def apply_schema(self, df: pd.DataFrame, filename: str) -> tuple[pd.DataFrame, bool]: ...

class AnalysisModule(ABC):
    """规定分析模块怎么执行分析。"""
    @abstractmethod
    def run(self, state: AppState) -> pd.DataFrame: ...

class UIComponent(ABC):
    """规定 UI 界面怎么构建。"""
    @abstractmethod
    def build(self, state: AppState) -> widgets.Widget: ...

# ════════════════════════════════════════════════════════════
# utils层
# ════════════════════════════════════════════════════════════
class UIUtils:
    @staticmethod
    def paginated_table(df: pd.DataFrame, title: str, rows_per_page: int = 5) -> widgets.VBox:
        """分页表格显示：如果数据有几万行，这个组件能保证一次只看5行。"""
        total = len(df)
        total_pages = max(1, (total + rows_per_page - 1) // rows_per_page)
        info_label = widgets.HTML(f'<b>{title}</b>（共 {total} 条，{total_pages} 页）')
        page_input = widgets.BoundedIntText(value=1, min=1, max=total_pages, description='跳转:', layout=widgets.Layout(width='120px'))
        btn_prev = widgets.Button(description='◀ 上一页', layout=widgets.Layout(width='100px'))
        btn_next = widgets.Button(description='下一页 ▶', layout=widgets.Layout(width='100px'))
        page_label = widgets.Label()
        table_out = widgets.Output(layout=widgets.Layout(border='1px solid #e0e0e0', padding='4px'))

        def _show(page: int):
            page_label.value = f'{page} / {total_pages}'
            with table_out:
                clear_output(wait=True)
                if df.empty:
                    print('暂无符合条件的数据')
                    return
                start = (page - 1) * rows_per_page
                display(df.iloc[start: start + rows_per_page].style.hide(axis='index'))

        page_input.observe(lambda c: _show(c['new']), names='value')
        btn_prev.on_click(lambda _: setattr(page_input, 'value', max(1, page_input.value - 1)))
        btn_next.on_click(lambda _: setattr(page_input, 'value', min(total_pages, page_input.value + 1)))
        _show(1)
        nav = widgets.HBox([btn_prev, page_input, page_label, btn_next], layout=widgets.Layout(align_items='center', gap='6px'))
        return widgets.VBox([info_label, nav, table_out])
# 进度条可视化工具
    @staticmethod
    def export_widget(df: pd.DataFrame, filename: str, label: str = '导出') -> widgets.HBox:
        """导出按钮：点一下就能把筛选出的结果表格下载到本地。"""
        btn = widgets.Button(description=label, button_style='warning', icon='download', layout=widgets.Layout(width='200px'))
        status = widgets.Output()

        def _on_export(_):
            with status:
                clear_output(wait=True)
                if df.empty: print('⚠️ 无数据'); return
                try:
                    df.to_csv(filename, index=False, encoding='utf-8-sig')
                    print(f'✅ 已导出：{filename}')
                except Exception as e: print(f'❌ 失败：{e}')

        btn.on_click(_on_export)
        return widgets.HBox([btn, status], layout=widgets.Layout(align_items='center', gap='8px'))
    @staticmethod
    def progress_bar(max_steps: int = 10) -> widgets.IntProgress:
    """
    创建一个标准进度条控件，默认隐藏，由 ProgressDriver 驱动。
    在 UI 的 build() 里调用，返回值放进 VBox 布局中。
    """
    return widgets.IntProgress(
        value=0,
        min=0,
        max=max_steps,
        description='加载进度',
        bar_style='info',
        layout=widgets.Layout(width='200px', display='none')
    )
class ProgressDriver:
    """
    进度条驱动器。
    封装 show / step / finish / hide 四个操作，
    挂载到任意分析模块的 _progress 属性即可驱动进度条。
    """

    def __init__(self, bar: widgets.IntProgress) -> None:
        self._bar = bar

    # ── 对外接口 ────────────────────────────────
    def step(self, value: int, desc: str | None = None) -> None:
        """推进到第 value 步，可选更新描述文字，并显示进度条。"""
        self._bar.layout.display = ''   # 首次调用时从隐藏变为可见
        self._bar.value = value
        if desc is not None:
            self._bar.description = desc

    def finish(self) -> None:
        """跳到最大值后隐藏，表示分析完成。"""
        self._bar.value = self._bar.max
        self._bar.description = '完成'
        self._bar.layout.display = 'none'

    def error(self) -> None:
        """标记为失败状态后隐藏。"""
        self._bar.bar_style = 'danger'
        self._bar.description = '失败'
        self._bar.layout.display = 'none'

    # ── 空对象（模块在没有进度条时调用不报错）────
    @staticmethod
    def noop() -> '_NoopDriver':
        """返回一个空实现，所有方法调用都静默忽略。"""
        return _NoopDriver()

class _NoopDriver:
    """空实现，让没有挂载进度条的模块调用 step/finish 时不报错。"""
    def step(self, value: int, desc: str | None = None) -> None: pass
    def finish(self) -> None: pass
    def error(self) -> None: pass
#
# 类定义  DateTimeUtils
class DateTimeUtils:
    _FORMATS = ('%Y%m%d%H%M%S', '%Y%m%d%H%M', '%Y%m%d', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d')

    @classmethod
    def robust_to_datetime(cls, series: pd.Series) -> pd.Series:
        """日期转换，兼容各种格式。"""
        warnings.filterwarnings('ignore', category=UserWarning)
        if pd.api.types.is_datetime64_any_dtype(series): return series
        def _parse(v):
            s = str(v).strip().replace('.0', '')
            if not s or s == 'nan': return pd.NaT
            for fmt in cls._FORMATS:
                try:
                    res = pd.to_datetime(s, format=fmt)
                    if not pd.isna(res): return res
                except: continue
            return pd.to_datetime(s, errors='coerce')
        return series.apply(_parse)

    @classmethod
    def clean_time_format(cls, series: pd.Series) -> pd.Series:
        """统一格式化为 YYYY-MM-DD HH:MM。"""
        s = series.astype(str).str.strip().str.replace(r'\.0$', '', regex=True)
        for fmt in cls._FORMATS:
            parsed = pd.to_datetime(s, format=fmt, errors='coerce')
            if parsed.notna().sum() > 0:
                return parsed.dt.strftime('%Y-%m-%d %H:%M')
        return pd.to_datetime(s, errors='coerce').dt.strftime('%Y-%m-%d %H:%M')

    @classmethod
    def fmt_date(cls, series: pd.Series) -> pd.Series:
        """格式化为 YYYY-MM-DD 日期字符串。"""
        return pd.to_datetime(series, errors='coerce').dt.strftime('%Y-%m-%d').fillna('')

    @classmethod
    def resolve_best_col(cls, df: pd.DataFrame, preferred: str, fallback: str) -> str | None:
        """从两个候选列中选出日期数据质量更好的那个。"""
        for col in (preferred, fallback):
            if col in df.columns:
                if cls.robust_to_datetime(df[col]).notna().sum() > len(df) * 0.3:
                    return col
        return None

class IdentityUtils:
    """嫌疑人身份推断工具：通过身份证号判性别和户籍区域。"""
    _NORTH = {'11','12','13','14','15','21','22','23','37','41','61','62','63','64','65'}
    _SOUTH = {'31','32','33','34','35','36','42','43','44','45','46','50','51','52','53','54'}

    @classmethod
    def gender(cls, id_str: str) -> Optional[str]: #callable
        """核心逻辑：看身份证倒数第二位，奇数是男，偶数是女。"""
        s = str(id_str).strip()
        if len(s) < 17 or not s[:17].isdigit(): return None
        return '男性' if int(s[16]) % 2 == 1 else '女性'

    @classmethod
    def region(cls, id_str: str) -> Optional[str]:
        """核心逻辑：根据身份证前两位代码判断属于南方还是北方。"""
        s = str(id_str).strip()
        if len(s) < 2: return None
        prefix = s[:2]
        return '北方' if prefix in cls._NORTH else ('南方' if prefix in cls._SOUTH else None)

    @classmethod
    def apply_filters(cls, df: pd.DataFrame, gender: str, region: str) -> pd.DataFrame:
        """一键画像筛选：给一个大表，按照设定的性别、地域条件自动过滤出嫌疑人。"""
        if df.empty or '身份证号' not in df.columns: return df
        result = df.copy()
        result['_id'] = result['身份证号'].astype(str).str.strip()
        if gender: result = result[result['_id'].apply(cls.gender) == gender]
        if region: result = result[result['_id'].apply(cls.region) == region]
        return result.drop(columns=['_id']).reset_index(drop=True)
#CPCO airportdata
class GeoUtils:
    """地理工具：查找地名对应的省份，或者机场代码对应的城市。"""
    def __init__(self):
        import airportsdata
        self._airports = airportsdata.load('IATA')

    def province_of(self, location: str) -> Optional[str]:
        """省份提取逻辑：调用 cpca 库自动解析地名中的省份。"""
        if not location: return None
        try:
            import cpca
            df_res = cpca.transform([str(location)])
            if not df_res.empty: return df_res.iloc[0]['省']
        except: pass
        return None

    def city_of_airport(self, iata_code: str) -> str:
        """机场翻译逻辑：输入 PEK 这种代码，返回其所在的城市名。"""
        val = str(iata_code).strip().upper()
        info = self._airports.get(val)
        return str(info['city']) if info and info.get('city') else val

#cell 2
# ── 全局字段注册表（所有模块在这里集中声明）──
AppState.register([
    # 文件上传模块
    SlotSpec('uploaded_frames',  dict,         '原始数据表 {filename: DataFrame}'),

    # 案件信息模块
    SlotSpec('case_points',      list,         '案发记录 [(日期, 城市), ...]'),
    SlotSpec('profile_gender',   str,          '嫌疑人性别'),
    SlotSpec('profile_region',   str,          '嫌疑人户籍'),
    SlotSpec('rental_company',   str,          '租赁公司名称'),
    SlotSpec('car_brand',        str,          '车辆品牌'),

    # 轨迹模块
    SlotSpec('matched_plates',        list,         '模糊搜索出的车牌号'),
    SlotSpec('matched_trajectories',  pd.DataFrame, '车牌对应详细轨迹记录'),

    # 租赁模块
    SlotSpec('df_real_car',      pd.DataFrame, '租赁全库匹配正式名单'),

    #住宿 / 车辆核查模块
    SlotSpec('current_lodging_res', pd.DataFrame, '住宿档案或车辆核查结果'),
    #租赁有案发轨迹模块
    SlotSpec('rental_trajectory_suspects', list, '租赁期内有轨迹记录的租车人姓名列表')

])

#cell 3
#数据文件存放
shared_state = AppState.instance()

#cell 4
#清空注册表数据（带二次确认逻辑）
btn_reset = widgets.Button(description='重置所有数据', button_style='danger', icon='trash')
btn_confirm = widgets.Button(description='是，确认重置', button_style='success')
btn_cancel = widgets.Button(description='否，点错了', button_style='warning')
confirm_box = widgets.HBox([widgets.Label('⚠️ 确定要清空所有已上传数据吗？'), btn_confirm, btn_cancel])
confirm_box.layout.display = 'none' # 初始隐藏

output_reset = widgets.Output()
state = AppState.instance()

def on_reset_click(_):
    confirm_box.layout.display = 'flex'
    btn_reset.layout.display = 'none'

def on_confirm_click(_):
    with output_reset:
        clear_output(wait=True)
        state.reset()
        print('✅ 所有数据已清空，可重新上传。')
        confirm_box.layout.display = 'none'
        btn_reset.layout.display = 'block'

def on_cancel_click(_):
    confirm_box.layout.display = 'none'
    btn_reset.layout.display = 'block'

btn_reset.on_click(on_reset_click)
btn_confirm.on_click(on_confirm_click)
btn_cancel.on_click(on_cancel_click)

display(widgets.VBox([btn_reset, confirm_box, output_reset]))

#cell 5
# # ── 注册本模块所需字段 ──────────────────────────────────────────
# AppState.register([
#     SlotSpec('uploaded_frames', dict, '原始数据表 {filename: DataFrame}'),
# ])
class FileUploadUI(UIComponent):
    """文件上传 UI，自适应 Colab / 本地 Jupyter。"""

    def __init__(self, data_source: DataSource):
        self._ds = data_source

    def build(self, state: AppState) -> widgets.Widget:
        output_area = widgets.Output()

        # 【输入层】：针对不同环境提供文件上传入口"
        if _is_colab():
            from google.colab import files as colab_files
            btn = widgets.Button(description='上传文件', button_style='info')

            def on_click(_):
                with output_area:
                    clear_output(wait=True)
                    print('请在弹出的对话框中选择文件…')
                # 弹出 Colab 专用上传窗口"
                uploaded = colab_files.upload()
                with output_area:
                    clear_output(wait=True)
                    if not uploaded:
                        print('⚠️  未选择任何文件')
                        return
                    # 将上传的文件字典交给数据源处理"
                    self._ds.process_files(uploaded, state, output_area)

            btn.on_click(on_click)
            return widgets.VBox([
                widgets.HTML('<h3>文件导入（支持Excel、CSV）</h3>'),
                btn, output_area
            ])
        else:
            upload_slot = widgets.Box()

            # 迭代处理本地 Jupyter 的上传内容 "
            def _iter(upload_value):
                iterable = upload_value.values() if isinstance(upload_value, dict) else upload_value
                for item in iterable:
                    if isinstance(item, dict):
                        yield item['metadata']['name'], bytes(item['content'])
                    else:
                        yield item.name, item.content.tobytes()

            def _attach():
                wu = widgets.FileUpload(
                    accept='.xls,.xlsx,.csv', multiple=True,
                    description='上传文件', button_style='info'
                )
                def on_upload(change):
                    payload = change['new']
                    if not payload: return
                    with output_area:
                        clear_output(wait=True)
                        self._ds.process_files(dict(_iter(payload)), state, output_area)
                    _attach() # 重新挂载以便多次上传"
                wu.observe(on_upload, names='value')
                upload_slot.children = (wu,)

            _attach()
            return widgets.VBox([
                widgets.HTML('<h3>文件导入（支持Excel、CSV）</h3>'),
                upload_slot, output_area
            ])

class FileDataSource(DataSource):
    """
    【处理层】：从字节流读取数据，并按预定义 Schema 规范化列名。
    """

    # 预设的列名模板（对应 DFD 中的数据字典定义）"
    _SCHEMAS: dict[str, list[str]] = {
        '航班': ['序号','姓名','身份证号','出发地','到达地','起飞时间','到达时间',
                 '航空公司','航班号','座位号','航班日期'],
        '机动车': ['序号','号牌种类','号牌号码','车辆品牌','车身颜色','所有人',
                   '身份证号','c8','c9','c10'],
        '轨迹': ['序号','号牌号码','号牌种类代码名称','通过时间','行政城市',
                 '行政区域','卡口名称'],
        '租赁': ['序号','租赁公司名称','号牌号码','车辆品牌','起租时间','停租时间',
                 '租车人姓名','租车人身份证号码','租车人联系方式'],
        '旅店': ['序号','姓名','身份证号','入住时间','退房时间','旅馆名称','房号',
                 '旅馆地址','所属派出所代码','所属派出所名称','真入住时间','真退房时间'],
    }
    _SCHEMAS['住宿'] = _SCHEMAS['旅店']
    _SCHEMAS['旅业'] = _SCHEMAS['旅店']

    # 需要精简保留的列
    _KEEP_COLUMNS: dict[str, list[str]] = {
        '机动车': ['序号','号牌种类','号牌号码','车辆品牌','车身颜色','所有人','身份证号'],
    }

    def load(self, content: bytes, filename: str) -> pd.DataFrame:
        """DFD - 数据转换：将原始字节流解析为 DataFrame"""
        stream = io.BytesIO(content)
        reader = pd.read_csv if filename.lower().endswith('.csv') else pd.read_excel
        # 跳过前2行（业务逻辑：通常前两行是无效表头或备注）
        return reader(stream, header=None, skiprows=2)

    def apply_schema(self, df: pd.DataFrame, filename: str) -> tuple[pd.DataFrame, bool]:
        """DFD - 数据清洗：通过文件名关键字匹配并强制转换列名"""
        for key, cols in self._SCHEMAS.items():
            if key in filename:
                result = df.copy()
                result.columns = cols
                if key in self._KEEP_COLUMNS:
                    result = result[self._KEEP_COLUMNS[key]]
                return result, True
        return df, False

    def process_files(
        self,
        files: dict[str, bytes],
        state: AppState,
        output: widgets.Output
    ) -> None:
        """DFD - 控制逻辑：循环处理文件流并输出反馈结果"""
        succeeded = failed = 0
        for filename, content in files.items():
            print(f'正在处理: {filename}…')
            try:
                # 1. 载入原始数据
                raw_df = self.load(content, filename)
                # 2. 映射标准列名
                df, matched = self.apply_schema(raw_df, filename)
                if not matched:
                    print('  ⚠️  未识别文件类型，保留原始列名')

                # 3. 输出存储：更新全局状态供其他模块调用
                state["uploaded_frames"][filename] = df
                print(f'  ✅ 上传成功！共 {len(df)} 条数据')
                succeeded += 1
            except Exception as exc:
                print(f'  ❌ 处理失败: {exc}')
                failed += 1

        # 【输出层】：在界面展示最终处理报告
        print(f"\n{'─'*40}")
        print(f'本次结果：成功 {succeeded} 个，失败 {failed} 个')
        print(f'累计已载入文件：{len(state["uploaded_frames"])} 个')

# 初始化全局状态
# 运行此单元格时，shared_state 就是所有后续单元格的数据纽带。
# shared_state = AppState.instance()
shared_data_source = FileDataSource()
display(FileUploadUI(shared_data_source).build(shared_state))

#cell 6
class CaseInfoUI(UIComponent):
    """案件基础信息录入 UI。"""

    def build(self, state: AppState) -> widgets.Widget:
        style = {'description_width': 'initial'}
        layout_s = widgets.Layout(width='300px')
        layout_b = widgets.Layout(width='150px')

        # 【输入层】：定义各种交互控件
        location_input    = widgets.Text(placeholder='输入案发城市关键字', description='1. 案发城市:', style=style, layout=layout_s)
        date_picker       = widgets.DatePicker(description='2. 案发时间:', value=date(2013, 11, 18), style=style, layout=layout_s)
        add_btn           = widgets.Button(description='确认添加', button_style='info', icon='plus', layout=layout_b)
        points_display    = widgets.Textarea(description='已保存记录:', disabled=True, layout=widgets.Layout(width='500px', height='80px'))
        gender_dd         = widgets.Dropdown(options=['','男性','女性'], value='', description='3. 嫌疑人性别:', style=style, layout=layout_s)
        region_dd         = widgets.Dropdown(options=['','南方','北方'], value='', description='4. 嫌疑人户籍:', style=style, layout=layout_s)
        rental_input      = widgets.Text(placeholder='如: 神州', description='5. 租赁公司:', style=style, layout=layout_s)
        brand_input       = widgets.Text(placeholder='如: 捷达', description='6. 车辆品牌:', style=style, layout=layout_s)
        btn_complete      = widgets.Button(description='完成', button_style='success', icon='check', layout=layout_b)

        # 二次确认逻辑相关的控件
        btn_clear_init    = widgets.Button(description='清空记录', button_style='danger', icon='trash', layout=layout_b)
        btn_clear_yes     = widgets.Button(description='是，确认清空', button_style='success', layout=widgets.Layout(width='100px'))
        btn_clear_no      = widgets.Button(description='否，点错了', button_style='warning', layout=widgets.Layout(width='100px'))
        clear_confirm_box = widgets.HBox([widgets.Label('确认清空记录？'), btn_clear_yes, btn_clear_no], layout=widgets.Layout(display='none'))
        output_info       = widgets.Output()

        def _refresh_view():
            points_display.value = (
                '[无记录]' if not state['case_points'] else
                '\n'.join(f'记录{i+1}: 地点={p[1]}, 时间={p[0]}'
                          for i, p in enumerate(state['case_points']))
            )

        def _sync_state():
           state['profile_gender'] = gender_dd.value
           state['profile_region'] = region_dd.value
           state['rental_company'] = rental_input.value.strip()
           state['car_brand']    = brand_input.value.strip()

        def on_add(_):
            loc = location_input.value.strip()
            if loc:
                state['case_points'].append((str(date_picker.value), loc))
                _refresh_view()
                location_input.value = ''
            else:
                with output_info:
                    clear_output()
                    print('⚠️ 请先输入案发地点！')

        def on_complete(_):
            _sync_state()
            with output_info:
                clear_output(wait=True)
                print('✅ 基础信息已录入完毕，请继续后续分析。')

        # 清空按钮的交互逻辑
        def on_clear_init_click(_):
            clear_confirm_box.layout.display = 'flex'
            btn_clear_init.layout.display = 'none'

        def on_clear_yes_click(_):
            state['case_points'] = []
            state['profile_gender'] = ''
            state['profile_region'] = ''
            state['rental_company'] = ''
            state['car_brand'] = ''
            gender_dd.value = ''
            region_dd.value = ''
            rental_input.value = ''
            brand_input.value = ''
            _refresh_view()
            clear_confirm_box.layout.display = 'none'
            btn_clear_init.layout.display = 'block'
            with output_info:
                clear_output()
                print('🔄 已清空记录！')

        def on_clear_no_click(_):
            clear_confirm_box.layout.display = 'none'
            btn_clear_init.layout.display = 'block'

        add_btn.on_click(on_add)
        btn_complete.on_click(on_complete)
        btn_clear_init.on_click(on_clear_init_click)
        btn_clear_yes.on_click(on_clear_yes_click)
        btn_clear_no.on_click(on_clear_no_click)

        return widgets.VBox([
            widgets.HTML('<b>2. 案件嫌疑人基础信息录入</b>'),
            location_input, date_picker, add_btn,
            points_display,
            gender_dd, region_dd,
            rental_input, brand_input,
            widgets.HBox([btn_complete, btn_clear_init, clear_confirm_box]),
            output_info,
        ])

display(CaseInfoUI().build(shared_state))

# cell 7

class FlightAnalysisUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        # 【输入层】：触发分析的按钮
        btn = widgets.Button(
            description='生成航班嫌疑人分析报告',
            button_style='primary',
            layout=widgets.Layout(width='250px')
        )

        # 【进度层】：默认隐藏，点击后再显示
        progress = UIUtils.progress_bar(max_steps=8)
        module._progress = ProgressDriver(progress)

        # 【输出层】：准备显示容器
        container = widgets.Output()
        module = FlightAnalysis(GeoUtils(), container)
        module._progress = progress  # 不改接口，内部挂载进度条

        btn.on_click(lambda _: module.run(state))
        return widgets.VBox([btn, progress, container])


class FlightAnalysis(AnalysisModule):
    """航班嫌疑人分析模块：通过案发时间、地点锁定嫌疑人。"""

    def __init__(self, geo: GeoUtils, output: widgets.Output):
        self._geo = geo
        self._output = output

    def run(self, state: AppState) -> pd.DataFrame:
        driver = getattr(self, '_progress', ProgressDriver.noop())
        driver.step(0, '开始加载')

        # 【处理层 - 数据准备】：从全局状态获取航班库和案发信息
        driver.step(1, '读取数据')
        df_raw = next(
            (df.copy() for fn, df in state['uploaded_frames'].items() if '航班' in fn),
            None
        )
        if not state['case_points'] or df_raw is None:
            with self._output:
                print('⚠️ 错误：没找到案发地点数据或航班数据库，请检查前面的步骤。')
            driver.error()
            return pd.DataFrame()

        # 【处理层 - 时间逻辑】：计算分析的时间窗口（首案前 vs 末案后）
        driver.step(2, '时间分析')
        sorted_pts = sorted(state['case_points'], key=lambda x: x[0])
        first_date = pd.to_datetime(sorted_pts[0][0])
        last_date = pd.to_datetime(sorted_pts[-1][0])

        # 【处理层 - 地理逻辑】：将案发城市名转换为省份关键字，用于匹配目的地
        driver.step(3, '地理匹配')
        crime_cities = [p[1] for p in state['case_points']]
        target_provinces = {
            (self._geo.province_of(c) or '').replace('省', '')
            for c in crime_cities
        }

        with self._output:
            clear_output(wait=True)
            print(f'💡 案发时间：{first_date.date()}  末案时间：{last_date.date()}')
            print(f'👤 画像：性别[{state["profile_gender"] or "不限"}]  户籍[{state["profile_region"] or "不限"}]')
            print('=' * 70)

        # 【处理层 - 清洗】：预处理日期和缺失值
        driver.step(4, '清洗数据')
        df_raw['航班日期'] = pd.to_datetime(df_raw['航班日期'], errors='coerce')
        df_raw = df_raw.dropna(subset=['航班日期', '身份证号'])

        relevant_cities: set[str] = set()

        def _is_target(code):
            # 内部逻辑：将机场代码转城市，再转省份进行碰撞
            city = self._geo.city_of_airport(code)
            prov = (self._geo.province_of(city) or '').replace('省', '')
            match = prov in target_provinces
            if match:
                relevant_cities.add(city)
            return match

        # 【处理层 - 空间筛选】：过滤出飞往案发相关区域的航班
        driver.step(5, '筛选表1')
        df_area = df_raw[df_raw['到达地'].apply(_is_target)].copy()

        with self._output:
            print(f' 案发城市附近相关机场城市：{list(relevant_cities)}')

            # 【输出层 - 表1】：筛选首案之前潜入该地区的嫌疑人（且符合画像特征）
            print(f'\n根据首案时间推导出嫌疑人在{first_date}之前到达案发城市 -> 表1')
            df_t1 = IdentityUtils.apply_filters(
                df_area[df_area['航班日期'] <= first_date].copy(),
                state["profile_gender"], state["profile_region"]
            )
            display(UIUtils.paginated_table(df_t1, ''))
            display(UIUtils.export_widget(df_t1, '首案前到达案发城市名单.csv.csv', '导出首案前到达案发城市名单'))

            # 【输出层 - 表2】：筛选末案之后离开的记录
            driver.step(6, '筛选表2')
            print(f'根据首案时间推导出嫌疑人在{last_date}之前离开案发城市 -> 表2')
            df_t2 = IdentityUtils.apply_filters(
                df_raw[df_raw['航班日期'] >= last_date].copy(),
                state["profile_gender"], state["profile_region"]
            )
            display(UIUtils.paginated_table(df_t2, ''))
            display(UIUtils.export_widget(df_t2, '末案后离开案发城市名单.csv', '导出末案后离开案发城市名单'))

            # 【处理层 - 核心碰撞】：计算表1和表2的交集（即：案前飞来，案后飞走的人）
            driver.step(7, '交集计算')
            print('\n根据首案、末案取公共乘客交集 -> 表3')
            if not df_t1.empty and not df_t2.empty:
                df_t3 = pd.merge(
                    df_t1,
                    df_t2[['姓名', '身份证号', '航班号', '航班日期']],
                    on=['姓名', '身份证号'], how='inner',
                    suffixes=('_进入', '_离开')
                )
            else:
                df_t3 = pd.DataFrame()

            # 【输出层 - 表3】：展示最终碰撞出的极高嫌疑名单
            display(UIUtils.paginated_table(df_t3, ''))
            display(UIUtils.export_widget(df_t3, '嫌疑人名单.csv.csv', '导出嫌疑人名单'))

            print('查询完毕')

        driver.step(8, '完成')
        self._hide_progress()
        return df_t3


# shared_state = AppState.instance()
display(FlightAnalysisUI().build(shared_state))

#cell 8
class PlateSearchUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        # 【输入层】：定义车牌片段输入框和查询按钮
        plate_input = widgets.Text(
            placeholder='输入已知车牌号片段，如辽CBS2',
            description='嫌疑车牌:',
            layout=widgets.Layout(width='300px')
        )
        out = widgets.Output()
        module = PlateSearchAnalysis(out)
        btn = widgets.Button(
            description='查询嫌疑车牌号',
            button_style='primary', icon='search',
            layout=widgets.Layout(width='150px')
        )
        btn.on_click(lambda _: module.run(state, plate_input.value.strip()))
        return widgets.VBox([
            widgets.HTML('<h3> 嫌疑车牌模糊查询</h3>'),
            widgets.HBox([plate_input, btn]),
            out
        ])

class PlateSearchAnalysis(AnalysisModule):
    """车牌模糊查询分析模块。"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState, pattern: str = '') -> pd.DataFrame:
        # 【处理层 - 1. 数据准备】：从全局状态载入轨迹库
        df_track = next(
            (df for fn, df in state['uploaded_frames'].items() if '轨迹' in fn),
            None
        )
        with self._output:
            clear_output(wait=True)
            if df_track is None:
                print('⚠️ 错误：未找到轨迹数据文件，请先上传！')
                return pd.DataFrame()
            if not pattern:
                print('⚠️ 请输入车牌号片段！')
                return pd.DataFrame()

            # 【处理层 - 2. 匹配算法】：将输入字符串转为大写，并转化为模糊匹配正则
            pattern_upper = pattern.upper()
            regex = '.*'.join(re.escape(c) for c in pattern_upper)
            regex = f'.*{regex}.*'

            # 使用 case=False 或将列转大写进行匹配
            mask = df_track['号牌号码'].str.upper().str.contains(regex, na=False, regex=True)

            # 【处理层 - 3. 结果整理】：按时间倒序排列并锁定匹配结果
            result = df_track[mask].sort_values('通过时间', ascending=False).copy()

            # 【处理层 - 4. 状态同步】：将锁定的车牌和轨迹存入全局状态供后续模块调用
            state['matched_trajectories'] = result
            state['matched_plates']  = list(result['号牌号码'].unique())

            # 【输出层】：渲染反馈信息和分页结果表
            if result.empty:
                print(f'❌ 未找到符合条件的号牌: {pattern_upper}')
            else:
                print(f'🔍 找到 {len(state["matched_plates"])} 辆车，共 {len(result)} 条轨迹。')
                display(UIUtils.paginated_table(result, ''))
                display(UIUtils.export_widget(result, '嫌疑车牌信息.csv.csv'))
        return result

display(PlateSearchUI().build(shared_state))

#cell 9
class SpatialPenetrationUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        slider = widgets.IntSlider(
            value=0, min=0, max=30, step=1,
            description='扩大搜索时间：在案发前后增加:',
            style={'description_width': 'initial'},
            layout={'width': '400px'}
        )
        unit_label = widgets.Label(value='天')
        out = widgets.Output()
        module = SpatialPenetrationAnalysis(out)
        btn = widgets.Button(
            description='查询', button_style='primary',
            icon='microchip', layout={'width': '100px'}
        )
        btn.on_click(lambda _: module.run(state, slider.value))
        return widgets.VBox([
            widgets.HTML('<h3>🛡️附加功能： 扩大搜索时间查询嫌疑车牌功能</h3>'),
            widgets.HTML("""
            <div style='background:#f8f9fa;padding:12px;border-radius:6px;
            font-size:12px;line-height:1.6;margin-bottom:10px;'>
            <b>🛡️ 使用说明：</b><br>
            数据来源：自动提取「嫌疑车牌模糊查询」锁定的嫌疑车牌。<br>
            处理逻辑：检查车牌在手动扩大搜索时间（已包含案发时间段）内是否出现在案发城市。<br>
            输出说明：展示嫌疑车辆轨迹明细并判断各车牌在案发城市是否出现。
            </div>"""),
            widgets.HBox([slider, unit_label, btn]),
              out
])

class PlateVerificationUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        plate_input = widgets.Text(
            placeholder='请输入完整车牌号(如: 辽A12345)',
            description='车牌号:',
            layout={'width': '350px'}
        )
        out = widgets.Output()
        module = PlateVerificationAnalysis(out)
        btn = widgets.Button(
            description='执行真伪核查',
            button_style='primary', icon='shield',
            layout={'width': '180px'}
        )
        btn.on_click(lambda _: module.run(state, plate_input.value.strip()))
        return widgets.VBox([
            widgets.HTML('<h3>🛡️附加功能： 车辆真伪查询</h3>'),
            widgets.HBox([plate_input, btn]),
            out
        ])

class SpatialPenetrationAnalysis(AnalysisModule):
    """时空分析模块"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState, buffer_days: int = 0) -> pd.DataFrame:
        # 【处理层 - 1. 数据准备】：获取轨迹库并验证前置条件
        df_track = next(
            (df for fn, df in state['uploaded_frames'].items() if '轨迹' in fn),
            None
        )
        with self._output:
            clear_output(wait=True)
            if not state['case_points']:
                print('⚠️ 错误：请先录入案发城市和日期。')
                return pd.DataFrame()
            if df_track is None:
                print('⚠️ 错误：未检测到轨迹数据库。')
                return pd.DataFrame()
            if not state['matched_plates']:
                print('⚠️ 错误：当前无锁定的嫌疑车牌，请先执行车牌搜索。')
                return pd.DataFrame()

            # 【处理层 - 2. 时间窗口计算】：根据案发记录自动计算分析的时间跨度（支持动态缓冲区）
            dates = [pd.to_datetime(p[0]) for p in state['case_points']]
            raw_start = min(dates)
            raw_end = max(dates)
            start = raw_start - timedelta(days=buffer_days)
            end = raw_end + timedelta(days=buffer_days)

            # 明确告诉用户本次筛选的时间范围
            print(f'📅 本次筛选时间范围：{start.date()} ～ {end.date()}')
            print(f'📌 原始案发时间范围：{raw_start.date()} ～ {raw_end.date()}')
            print(f'📌 扩大搜索时间：前后各 {buffer_days} 天')
            print('-' * 70)

            # 【处理层 - 3. 空间匹配逻辑】：构建案发城市正则，在轨迹库中匹配卡口或区域名称
            cities = [p[1] for p in state['case_points']]
            loc_re = '|'.join(cities)

            df_track = df_track.copy()
            df_track['通过时间'] = pd.to_datetime(df_track['通过时间'])
            mask = (
                df_track['号牌号码'].isin(state['matched_plates']) &
                df_track['通过时间'].between(start, end) &
                (
                    df_track['卡口名称'].str.contains(loc_re, na=False) |
                    df_track['行政区域'].str.contains(loc_re, na=False)
                )
            )
            result = df_track[mask].sort_values('通过时间').copy()

            # 【输出层】：渲染明细表和汇总状态报告
            if result.empty:
                print(f'❌ 在设定时空范围内，嫌疑车牌未发现任何轨迹。')
            else:
                print(f'✅ 共发现 {len(result)} 条关联轨迹。')
                display(UIUtils.paginated_table(result, '嫌疑车辆轨迹明细'))
                display(UIUtils.export_widget(result, '嫌疑车辆轨迹信息表.csv.csv'))

                print('\n嫌疑车辆分布状态汇总：')
                for plate in state['matched_plates']:
                    sub = result[result['号牌号码'] == plate]
                    parts = []
                    for city in cities:
                        found = (
                            sub['卡口名称'].str.contains(city, na=False).any() |
                            sub['行政区域'].str.contains(city, na=False).any()
                        )
                        parts.append(f'【{city}】：{"是" if found else "否"}')
                    print(f'🚗 {plate} -> {" | ".join(parts)}')
        return result

class PlateVerificationAnalysis(AnalysisModule):
    """车辆真伪核查模块"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState, plate: str = '') -> pd.DataFrame:
        # 【处理层 - 1. 数据源检索】：加载机动车库和租赁库
        df_vehicle = next(
            (df for fn, df in state['uploaded_frames'].items() if '机动车' in fn),
            pd.DataFrame()
        )
        df_rental = next(
            (df for fn, df in state['uploaded_frames'].items() if '租赁' in fn),
            pd.DataFrame()
        )
        with self._output:
            clear_output(wait=True)
            if not plate:
                print('⚠️ 请输入需要核查的完整车牌号！')
                return pd.DataFrame()

            # 统一转换为大写进行核查
            plate_upper = plate.upper()
            parts = []
            # 【处理层 - 2. 数据库碰撞】：分别在登记库和租赁库中精准查询该车牌
            if not df_vehicle.empty:
                res_v = df_vehicle[df_vehicle['号牌号码'] == plate_upper].copy()
                if not res_v.empty:
                    res_v['备案来源'] = '机动车登记库'
                    res_v['身份结论'] = '真牌 (个人/单位)'
                    parts.append(res_v)

            if not df_rental.empty:
                res_r = df_rental[df_rental['号牌号码'] == plate_upper].copy()
                if not res_r.empty:
                    res_r['备案来源'] = '汽车租赁库'
                    res_r['身份结论'] = '真牌 (租赁车辆)'
                    res_r = res_r.rename(columns={'租车人姓名': '所有人'})
                    parts.append(res_r)

            # 【输出层】：整合核查结果并展示详细档案
            combined = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()
            state['current_lodging_res'] = combined

            print(f'--- {plate_upper} 核查报告 ---')
            if combined.empty:
                print('在[机动车信息库]和[租赁信息库]中均未发现备案记录！')
                print('结论：该车为假牌。')
            else:
                print('✅ 已在数据库中匹配到备案档案。')
                display(UIUtils.paginated_table(combined, '备案详细档案'))
                display(UIUtils.export_widget(combined, f'{plate_upper}.csv.csv'))
        return combined

display(SpatialPenetrationUI().build(shared_state))
display(PlateVerificationUI().build(shared_state))

#cell 10
class RentalAnalysisUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        out = widgets.Output()
        module = RentalAnalysis(out)
        btn = widgets.Button(
            description='查询租赁信息',
            button_style='primary', icon='link',
            layout=widgets.Layout(width='150px')
        )
        btn.on_click(lambda _: module.run(state))
        return widgets.VBox([btn, out])

class RentalAnalysis(AnalysisModule):
    """租赁全库分析模块。"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState) -> pd.DataFrame:
        # 【处理层 - 1. 数据准备】：从状态库加载租赁表与轨迹表
        df_rental = next(
            (df for fn, df in state['uploaded_frames'].items() if '租赁' in fn),
            pd.DataFrame()
        )
        df_track = next(
            (df for fn, df in state['uploaded_frames'].items() if '轨迹' in fn),
            pd.DataFrame()
        )
        with self._output:
            clear_output()
            if not state['case_points']:
                print('⚠️ 错误：未检测到案发时间，请在基础信息模块录入。')
                return pd.DataFrame()
            if df_rental.empty:
                print('⚠️ 错误：未发现租赁数据库，请先导入文件。')
                return pd.DataFrame()

            # 【处理层 - 2. 时间窗口】：计算案发时段（最早到最晚）
            case_dates = sorted(pd.to_datetime(p[0]) for p in state['case_points'])
            earliest, latest = case_dates[0], case_dates[-1]

            df_rental = df_rental.copy()
            df_rental['起租时间'] = pd.to_datetime(df_rental['起租时间'], errors='coerce')
            df_rental['停租时间'] = pd.to_datetime(df_rental['停租时间'], errors='coerce')

            # 【处理层 - 3. 时空与品牌过滤】：锁定案发期间一直处于租赁状态的车辆
            mask = (df_rental['起租时间'] <= earliest) & (df_rental['停租时间'] >= latest)
            if state['rental_company']:
                mask &= df_rental['租赁公司名称'].str.contains(state['rental_company'], na=False)
            if state['car_brand']:
                mask &= df_rental['车辆品牌'].astype(str) == state['car_brand']

            df_confirmed = df_rental[mask].copy()

            if df_confirmed.empty:
                print('❌ 库中未发现符合条件的记录。')
                return pd.DataFrame()

            # 【输出层 - 1】：展示符合条件的租车名单
            state['df_real_car'] = df_confirmed
            display(UIUtils.paginated_table(df_confirmed, '符合案发地点、案发时间的租车备案名单'))
            display(UIUtils.export_widget(df_confirmed, '导出租车备案名单.csv.csv', '导出租车备案名单'))

            # 【处理层 - 4. 轨迹查询】：将租车人与轨迹进行时空碰撞，确保轨迹发生在租赁期内
            if not df_track.empty:
                df_track = df_track.copy()
                df_track['通过时间'] = pd.to_datetime(df_track['通过时间'], errors='coerce')
                merged = pd.merge(
                    df_confirmed[['号牌号码','租车人姓名','租车人身份证号码','起租时间','停租时间']],
                    df_track[['号牌号码','通过时间','卡口名称','行政区域']],
                    on='号牌号码', how='inner'
                )
                # 核心筛选：轨迹时间必须在起租和停租之间
                merged = merged[
                    (merged['通过时间'] >= merged['起租时间']) &
                    (merged['通过时间'] <= merged['停租时间'])
                ]
                if not merged.empty:
                    state['rental_trajectory_suspects'] = list(merged['租车人姓名'].unique())
                    # 【输出层 - 2】：展示租赁期内的详细轨迹路径
                    display(widgets.HTML('<hr>'))
                    display(UIUtils.paginated_table(merged.sort_values('通过时间'), '租赁期内轨迹查询明细'))
                    display(UIUtils.export_widget(merged, '导出租赁-轨迹表.csv.csv', '导出租赁-轨迹表'))
        return df_confirmed

display(RentalAnalysisUI().build(shared_state))

#cell 11
class LodgingQueryUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        # 【输出层】：准备同步显示区域和过滤输入框
        ref_out = widgets.Output()
        filter_input = widgets.Text(
            placeholder='输入姓名或身份证号筛选...',
            description='筛选:',
            layout={'width': '400px', 'display': 'none'}
        )

        # 【处理层 - 辅助逻辑】：刷新并同步已锁定的租赁人员参考名单
        def _refresh(b=None):
            with ref_out:
                clear_output()
                if state['df_real_car'].empty:
                    filter_input.layout.display = 'none'
                    print('提示：未检测到已锁定的租赁嫌疑人，请先执行租赁全库分析。')
                    return
                cols = ['租车人姓名','租车人身份证号码','号牌号码','车辆品牌']
                existing = [c for c in cols if c in state['df_real_car'].columns]
                suspects = state['df_real_car'][existing].drop_duplicates()
                q = filter_input.value.strip()
                if q:
                    suspects = suspects[suspects.apply(lambda r: q in str(r.values), axis=1)]
                filter_input.layout.display = 'flex'
                print(f'[同步成功] 已锁定租车人参考名单 (共 {len(suspects)} 人)：')
                display(suspects.style.hide(axis='index'))

        # 【输入层】：绑定同步按钮和筛选观察器
        filter_input.observe(lambda _: _refresh(), names='value')
        btn_ref = widgets.Button(description='同步备案租车名单', button_style='info', layout={'width': '250px'})
        btn_ref.on_click(_refresh)

        # 【输入层】：个人信息手动查询框
        search_id   = widgets.Text(description='身份证号:', layout={'width': '350px'})
        search_name = widgets.Text(description='姓名:', layout={'width': '350px'})
        search_out  = widgets.Output()
        module = LodgingQueryAnalysis(search_out)
        btn_search = widgets.Button(description='搜索个人住宿档案', button_style='primary', layout={'width': '180px'})
        btn_search.on_click(lambda _: module.run(state, search_id.value.strip(), search_name.value.strip()))

        return widgets.VBox([
            widgets.HTML('<h3>嫌疑人/司机住宿档案查询系统</h3>'),
            widgets.HTML("<p style='color:#666;'>步骤1: 同步已锁定的租赁人员名单</p>"),
            widgets.HBox([btn_ref, filter_input]),
            ref_out,
            widgets.HTML("<hr style='border:1px dashed #ccc;'>"),
            widgets.HTML("<p style='color:#666;'>步骤2: 输入信息查询其历史住宿记录</p>"),
            widgets.HBox([search_id, search_name]),
            btn_search,
            search_out
        ])

class CohabitAnalysisUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        # 【输出层】：准备显示容器
        out = widgets.Output()
        module = CohabitAnalysis(out)

        # 【输入层】：同住关联分析触发按钮
        btn = widgets.Button(
            description='嫌疑人（司机）同住关联分析查询',
            button_style='primary', icon='users',
            layout=widgets.Layout(width='250px')
        )
        btn.on_click(lambda _: module.run(state))
        return widgets.VBox([
            widgets.HTML('<h3>🏨 嫌疑人同住轨迹交叉分析</h3>'),
            btn, out
        ])

class LodgingQueryAnalysis(AnalysisModule):
    """住宿档案查询模块。"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState, id_val: str = '', name_val: str = '') -> pd.DataFrame:
        # 【处理层 - 1. 数据准备】：从全局状态搜索住宿/旅店库
        df_hotel = next(
            (df for fn, df in state['uploaded_frames'].items()
             if any(k in fn for k in ['旅店','住宿','旅业'])),
            pd.DataFrame()
        )
        with self._output:
            clear_output()
            if df_hotel.empty:
                print('错误：未检测到住宿数据库，请先上传数据文件。')
                return pd.DataFrame()
            if not id_val and not name_val:
                print('请输入身份证号或姓名进行查询。')
                return pd.DataFrame()

            # 【处理层 - 2. 精准过滤】：根据身份证或姓名匹配记录
            mask = (
                df_hotel['身份证号'].astype(str) == id_val
                if id_val else df_hotel['姓名'] == name_val
            )
            res = df_hotel[mask].copy()

            if res.empty:
                state['current_lodging_res'] = pd.DataFrame()
                print('查询结束：在住宿库中未找到相关记录。')
                return pd.DataFrame()

            # 【处理层 - 3. 时间清洗】：格式化显示所有日期字段，统一视觉表现
            for col in ['入住时间','退房时间','真入住时间','真退房时间']:
                if col in res.columns:
                    res[col] = DateTimeUtils.clean_time_format(res[col])

            # 【输出层】：保存结果至状态并渲染分页表格
            state['current_lodging_res'] = res
            core = ['姓名','身份证号','入住时间','退房时间','旅馆名称','房号','旅馆地址']
            display(UIUtils.paginated_table(
                res[[c for c in core if c in res.columns]],
                f'嫌疑人 {name_val or id_val} 的住宿档案详情'
            ))
        return res

class CohabitAnalysis(AnalysisModule):
    """同住关联分析模块。"""

    def __init__(self, output: widgets.Output):
        self._output = output

    def run(self, state: AppState) -> pd.DataFrame:
        # 【处理层 - 1. 数据准备】：调取住宿库及租赁分析已锁定的名单
        df_hotel = next(
            (df for fn, df in state['uploaded_frames'].items()
             if any(k in fn for k in ['旅店','住宿','旅业'])),
            pd.DataFrame()
        )
        with self._output:
            clear_output(wait=True)
            if df_hotel.empty:
                print('❌ 错误：未检测到住宿数据库，请先上传数据。')
                return pd.DataFrame()
            if state['df_real_car'].empty:
                print('⚠️ 错误：未检测到已锁定的租赁嫌疑人，请先执行租赁全库分析。')
                return pd.DataFrame()

            suspect_names = state['rental_trajectory_suspects']
            if not suspect_names:
                print('⚠️ 错误：未检测到租赁期内轨迹嫌疑人，请先执行租赁全库分析。')
                return pd.DataFrame()

            # 【处理层 - 辅助】：强力日期转换工具
            def _to_dt(series: pd.Series) -> pd.Series:
                s = series.astype(str).str.strip().str.replace(r'\.0$', '', regex=True)
                return pd.to_datetime(s, errors='coerce', format='%Y%m%d%H%M')

            all_results: list[pd.DataFrame] = []
            # 【处理层 - 2. 核心分析循环】：对每个租车人执行时空关联分析
            for name in suspect_names:
                print(f"\n{'='*60}\n🔍 分析 '{name}' 的同住关联...\n")
                base = df_hotel[df_hotel['姓名'] == name].copy()
                if base.empty:
                    print(f'❌ 住宿库中未找到 "{name}" 的记录，跳过。')
                    continue

                base['dt'] = _to_dt(base['入住时间'])
                pool = df_hotel.copy()
                pool['dt'] = _to_dt(pool['入住时间'])
                pool = pool.dropna(subset=['dt','旅馆名称'])

                hits: list[pd.DataFrame] = []
                for _, row in base.iterrows():
                    # 【处理层 - 核心碰撞算法】：同一旅馆 + 入住时间差 24 小时内
                    window = pd.Timedelta(hours=24)
                    m = (
                        (pool['旅馆名称'] == row['旅馆名称']) &
                        pool['dt'].between(row['dt'] - window, row['dt'] + window)
                    )
                    h = pool[m].copy()
                    h['关联基准人'] = name
                    h['同住关系'] = h['姓名'].apply(lambda x: '本人' if x == name else '潜在同行人')
                    hits.append(h)

                if not hits:
                    print(f'未发现 "{name}" 的同住关联人员。')
                    continue

                # 【处理层 - 3. 结果去重与整理】：移除重复碰撞，并规范时间显示
                df_final = pd.concat(hits).drop_duplicates(
                    subset=['姓名','身份证号','入住时间','旅馆名称']
                )
                df_final['入住时间_标准'] = df_final['dt'].dt.strftime('%Y-%m-%d %H:%M')
                cols = ['姓名','身份证号','同住关系','入住时间_标准','旅馆名称','房号','旅馆地址']
                others = df_final[df_final['同住关系'] != '本人']

                # 【输出层】：渲染该嫌疑人的关联分析报表并提供 CSV 导出
                print(f'✅ "{name}" 关联发现 {len(others)} 名潜在同行人员。')
                display(UIUtils.paginated_table(
                    df_final[cols].sort_values(['入住时间_标准','同住关系']),
                    f' {name} 同住关联分析报告'
                ))
                display(UIUtils.export_widget(df_final[cols], f'{name}_cohort_analysis.csv'))
                all_results.append(df_final[cols])

        return pd.concat(all_results, ignore_index=True) if all_results else pd.DataFrame()

display(LodgingQueryUI().build(shared_state))
display(CohabitAnalysisUI().build(shared_state))

#cell 12
_HOTEL_DISPLAY_COLS = [
    '姓名', '身份证号',
    '关联案发点', '对应案发日期', '筛选时间窗口',
    '入住日期', '退房日期',
    '旅馆名称', '房号', '旅馆地址',
]


class HotelPreprocessor:
    def preprocess(self, df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
        warn: list[str] = []
        df = df.copy()
        ci_col = DateTimeUtils.resolve_best_col(df, '真入住时间', '入住时间')
        df['_checkin_dt']  = DateTimeUtils.robust_to_datetime(df[ci_col]) if ci_col else pd.NaT
        co_col = DateTimeUtils.resolve_best_col(df, '真退房时间', '退房时间')
        df['_checkout_dt'] = DateTimeUtils.robust_to_datetime(df[co_col]) if co_col else pd.NaT
        df['入住日期'] = DateTimeUtils.fmt_date(df['_checkin_dt'])
        df['退房日期'] = DateTimeUtils.fmt_date(df['_checkout_dt'])
        return df, warn
 #上述为这个模块特对的业务逻辑 需要解析时间 处理输出格式 并非所有模块都需要 具体问题具体分析
class HotelPenetrationAnalysis(AnalysisModule):
    _REQUIRED_COLS = {'旅馆地址', '旅馆名称', '姓名', '身份证号'}

    def __init__(self, output: widgets.Output):
        self._output = output
        self._preprocessor = HotelPreprocessor()

    def run(self, state: AppState) -> pd.DataFrame:
        with self._output:
            clear_output(wait=True)
            df_raw = self._get_hotel_df(state)
            if not self._validate(df_raw, state['case_points']): return pd.DataFrame()

            df_hotel, _ = self._preprocessor.preprocess(df_raw)
            df_valid = df_hotel[df_hotel['_checkin_dt'].notna()].copy()
            if state['profile_gender'] or state['profile_region']:
                df_valid = IdentityUtils.apply_filters(df_valid, state['profile_gender'], state['profile_region'])

            # 1. 动态筛选每个案发点的人员名单
            point_results = []
            for case_date_str, loc_keyword in state['case_points']:
                target_dt = pd.to_datetime(case_date_str)
                window_start = target_dt - timedelta(days=1)
                loc_mask = (df_valid['旅馆地址'].astype(str).str.contains(loc_keyword, na=False) |
                            df_valid['旅馆名称'].astype(str).str.contains(loc_keyword, na=False))
                time_mask = df_valid['_checkin_dt'].between(window_start, target_dt)
                hits = df_valid[loc_mask & time_mask].copy()
                hits['关联案发点'] = loc_keyword
                hits['对应案发日期'] = case_date_str
                hits['筛选时间窗口'] = f'{window_start.date()} ~ {target_dt.date()}'
                point_results.append(hits)

            if not point_results: return pd.DataFrame()

            # 2. 核心逻辑：身份证号动态取交集
            intersection_ids = set(point_results[0]['身份证号'].unique())
            for res in point_results[1:]:
                intersection_ids &= set(res['身份证号'].unique())

            if not intersection_ids:
                print(f'❌ 分析结束：未发现同时在 {len(point_results)} 个案发地点出现的嫌疑人。')
                return pd.DataFrame()

            # 3. 提取交集人员的所有相关记录并汇总
            df_all_hits = pd.concat(point_results, ignore_index=True)
            df_final = df_all_hits[df_all_hits['身份证号'].isin(intersection_ids)].copy()

            show_cols = [c for c in _HOTEL_DISPLAY_COLS if c in df_final.columns]
            print(f'查询完成！共找到 {len(intersection_ids)} 名嫌疑人，汇总记录 {len(df_final)} 条。')
            display(UIUtils.paginated_table(df_final[show_cols], '共同嫌疑人住宿总表'))
            display(UIUtils.export_widget(df_final[show_cols], '共同嫌疑人住宿名单.csv', '导出共同嫌疑人住宿名单.csv'))
            return df_final

    def _get_hotel_df(self, state: AppState) -> pd.DataFrame:
        for fname, df in state['uploaded_frames'].items():
            if any(k in fname for k in ['旅店', '住宿', '旅业']): return df.copy()
        return pd.DataFrame()

    def _validate(self, df_raw, case_points) -> bool:
        if not case_points or df_raw.empty:
            print('⚠️ 缺少案发信息或住宿数据'); return False
        return True

class HotelPenetrationUI(UIComponent):
    def build(self, state: AppState) -> widgets.Widget:
        container = widgets.Output()
        module = HotelPenetrationAnalysis(container)
        btn = widgets.Button(description='嫌疑人共同住宿查询', button_style='primary', icon='crosshairs', layout=widgets.Layout(width='250px'))
        btn.on_click(lambda _: module.run(state))
        return widgets.VBox([btn, container])

display(HotelPenetrationUI().build(shared_state))